### ISSUE TITLE
Bundle download - Store metadata and resolve hard coding path issues

### ISSUE THREAD

**Issue by deepakduggirala** [IUSCA/bioloop#102]
Store name, md5 scheksum, size (currently - dataset.bundle_size) in the dataset_file table.

Storing bundle in dataset_file shouldn't impact the file listing APIs.

Bundle is assumed to be always a tar file and this is hard coded while constructing paths in UI, API, Workers code.

The download alias directory `download/<alias>` is symlinked to `stage/<alias>/<dataset_name>`. This is because of FACL constraints.  This is an issue now because the bundle file is staged to `stage/<alias>/<dataset_name>.tar` and symlinked to `download/<alias>/<dataset_name>.tar`. This placement makes it look like `<dataset_name>.tar` is inside the dataset and as one of the files of the dataset for end users looking in `download/<alias>`

Show a button to download the bundle in the dataset page (it is being shown in project page now)

#37 seems easy enough to fix in this ticket.

**Comment by ri-pandey** [comment]
This will require the following steps to be performed before/after release:

## Before Release

1. Add the following properties to `production.py`:
```
# Key                                                                    Value (in dev - will need to be edited based on env)
config['paths']['RAW_DATA']['bundle']               /N/scratch/scadev/bioloop/dev/staged/raw_data/bundles
config['paths']['DATA_PRODUCT']['bundle']     /N/scratch/scadev/bioloop/dev/staged/data_products/bundles
```
To make it clearer, these values are basically existing property's values, followed by `/bundles`, like so:
```
config['paths']['RAW_DATA']['stage'] / bundles
config['paths']['DATA_PRODUCT']['stage'] / bundles
```

2. Do a Prisma migration so that the new table is created
```
npx prisma migrate deploy
```

## After Release

First, restart the pm2 env, since the ecosystem.config.js file was modified in this ticket.

After pm2 is restarted, the script `workers/workers/scripts/populate_bundles.py` will need to be run. This script will download archived datasets from the SDA, and after checksum verification, evaluate bundle metadata for these bundles, and persist it to the `bundle` table.

This is necessary for the already archived datasets to be downloadable.

Steps (after restarting poetry):
```
pm2 ls
# note down id of the populate_bundles task
pm2 restart [id of populate_bundles task]
```
