### ISSUE TITLE
Ingest from Slate-scratch

### ISSUE THREAD

**Issue by ri-pandey** [IUSCA/bioloop#142]
This is a follow up of ticket #99. The intention is to enable the dataset ingestion from the Slate-Scratch filesystem.

**Comment by deepakduggirala** [comment]
Added a couple of APIs to secure download server to show directory listings and sizes given a path. The code is in [operator-data-import](https://github.com/IUSCA/bioloop/tree/operator-data-import) branch.

Added service in UI code to call these APIs and a sample page ([/datasets/import](https://localhost/datasets/import)) to test the functionality.

The size API is not a typical request-response, but a Server Sent Event (SSE) style API. This is made because it can take long to get size of a directory especially on mounted file systems such as Slate Project / Slate Scratch. By making this SSE, http connection will be kept alive till the size is computed.

TODO:
No auth is set up yet.

Download routes are moved under /download but the client code is not updated yet. So downloading files will not work.

**Comment by ri-pandey** [comment]
Release notes:

1. Add the following properties to `api/.env`:
```
FILESYSTEM_SEARCH_SPACES=/space1/path,/space2/path
FILESYSTEM_BASE_DIR_SCRATCH=/path/to/scratch/base/dir
FILESYSTEM_MOUNT_DIR_SCRATCH=/path/to/scratch/mount/dir
SCRATCH_INGESTION_RESTRICTED_DIRS=/path/to/scratch/restricted/dir
FILESYSTEM_BASE_DIR_PROJECT=/path/to/project/base/dir
FILESYSTEM_MOUNT_DIR_PROJECT=/path/to/project/mount/dir
PROJECT_INGESTION_RESTRICTED_DIRS=/path/to/project/restricted/dir
```
2. Add the following properties to `ui/.env`:
```
VITE_SCRATCH_BASE_DIR=/path/to/scratch/base_dir
VITE_SCRATCH_MOUNT_DIR=/path/to/scratch/mount_dir
VITE_SCRATCH_INGESTION_RESTRICTED_DIRS=/pattern/to/match/multiple/restricted/dirs/**/*,path/to/single/restricted/dir
VITE_PROJECT_BASE_DIR=/path/to/project/base_dir
VITE_PROJECT_MOUNT_DIR=/path/to/project/mount_dir
VITE_PROJECT_INGESTION_RESTRICTED_DIRS=/pattern/to/match/multiple/restricted/dirs/*,path/to/single/restricted/dir

VITE_FILESYSTEM_SEARCH_SPACES=/path/to/space1,/path/to/space2
```
